/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Order;

import com.homePage.HomePage;
import com.util.DatabaceConnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import screens.castomarCopy;
import static sun.net.www.MimeTable.loadTable;
 

/**
 *
 * @author Khalil
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        setLocationRelativeTo(null);
        Calendar();
        loadTable();
    }

    public void Calendar() {
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        tfDate.setText(+year + "-" + (month + 1) + "-" + day);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmNext = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfDLViD = new javax.swing.JTextField();
        tfTrackId = new javax.swing.JTextField();
        tfNameP = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        adressP = new javax.swing.JTextArea();
        tfphoneP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        coomDOtypP = new javax.swing.JComboBox<>();
        tfContentsP = new javax.swing.JTextField();
        comWgtP = new javax.swing.JComboBox<>();
        tfQuantityP = new javax.swing.JTextField();
        tfAmountP = new javax.swing.JTextField();
        tfnameS = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        adressS = new javax.swing.JTextArea();
        tfPhoneS = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfDate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tfTrakingNo2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tfContents2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        comWgt2 = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        texaria3 = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        coomDOtype2 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        tfAmount2 = new javax.swing.JTextField();
        tfQuantity2 = new javax.swing.JTextField();
        btnSave1 = new javax.swing.JButton();
        tfName3 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        tfPhone3 = new javax.swing.JTextField();
        tfId2 = new javax.swing.JTextField();
        btnReset1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        picTable2 = new javax.swing.JTable();
        btnSave4 = new javax.swing.JButton();
        comStatus = new javax.swing.JComboBox<>();
        btmReset = new javax.swing.JButton();
        btnUpdate2 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btmNext.setBackground(new java.awt.Color(0, 204, 255));
        btmNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btmNext.setForeground(new java.awt.Color(102, 0, 102));
        btmNext.setText("Next");
        btmNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmNextActionPerformed(evt);
            }
        });
        getContentPane().add(btmNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 100, 40));

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order Table");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(88, 88, 88)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("From.....");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Name:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 92, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Adress");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 78, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Phone No.");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 92, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("To.....");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 70, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 78, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 119, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Delivery ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 101, 32));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Tracking No.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 92, 32));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Name:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 92, 32));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Adress");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 92, 32));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Phone No.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 92, 32));
        getContentPane().add(tfDLViD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 204, 32));
        getContentPane().add(tfTrackId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 204, 32));

        tfNameP.setText(" ");
        getContentPane().add(tfNameP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 204, 32));

        adressP.setColumns(20);
        adressP.setRows(5);
        jScrollPane3.setViewportView(adressP);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 204, 38));

        tfphoneP.setText(" ");
        getContentPane().add(tfphoneP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 204, 32));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Document Type:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 109, 32));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Contants");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 92, 32));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Waight");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 119, 32));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Quantity:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 92, 32));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Amount:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 102, 32));

        coomDOtypP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coomDOtypP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Chose One...", "Document", "None Document" }));
        getContentPane().add(coomDOtypP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 161, 32));

        tfContentsP.setText(" ");
        getContentPane().add(tfContentsP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 157, 32));

        comWgtP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comWgtP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "How Waight", "50 gram.", "100 gram", "500 gram", "1 KG", "2 KG", "5 KG", "10 KG" }));
        getContentPane().add(comWgtP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 157, 32));

        tfQuantityP.setText(" ");
        getContentPane().add(tfQuantityP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 157, 32));

        tfAmountP.setText(" ");
        getContentPane().add(tfAmountP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 160, 32));

        tfnameS.setText(" ");
        getContentPane().add(tfnameS, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 204, 32));

        adressS.setColumns(20);
        adressS.setRows(5);
        jScrollPane4.setViewportView(adressS);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 204, 38));

        tfPhoneS.setText(" ");
        getContentPane().add(tfPhoneS, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 204, 32));

        jPanel5.setBackground(new java.awt.Color(102, 0, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 10, 290));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, 30));

        tfDate.setText(" ");
        getContentPane().add(tfDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 140, 30));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(102, 193, 182));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Delivery ID");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Waight");

        tfContents2.setText(" ");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Adress");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Phone No.");

        comWgt2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comWgt2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "How Waight", "50 gram.", "100 gram", "500 gram", "1 KG", "2 KG", "5 KG", "10 KG" }));

        texaria3.setColumns(20);
        texaria3.setRows(5);
        jScrollPane5.setViewportView(texaria3);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("Document Type:");

        coomDOtype2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coomDOtype2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Chose One...", "Document", "None Document" }));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Contants");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setText("Amount:");

        tfAmount2.setText(" ");

        tfQuantity2.setText(" ");

        btnSave1.setBackground(new java.awt.Color(153, 153, 0));
        btnSave1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave1.setForeground(new java.awt.Color(255, 255, 255));
        btnSave1.setText("SAVE");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        tfName3.setText(" ");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setText("Tracking No.");

        tfPhone3.setText(" ");

        btnReset1.setBackground(new java.awt.Color(153, 153, 0));
        btnReset1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset1.setForeground(new java.awt.Color(255, 255, 255));
        btnReset1.setText("Reset");

        btnUpdate1.setBackground(new java.awt.Color(153, 153, 0));
        btnUpdate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setText("Quantity:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfContents2)
                            .addComponent(tfTrakingNo2)
                            .addComponent(coomDOtype2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfPhone3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfId2)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(tfName3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane5)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addComponent(tfAmount2)
                            .addComponent(comWgt2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfQuantity2))))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(248, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfId2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTrakingNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfName3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPhone3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coomDOtype2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(tfContents2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comWgt2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfQuantity2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(380, Short.MAX_VALUE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(91, 91, 91)))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Order Details");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(450, 450, 450)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 890, 50));

        picTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tracking No.", "Name", "Address", "Phone No.", "Date", "Document Type", "Contant", "Waight", "Quantity", "Amount", "Name", "Adress", "Phone", "status"
            }
        ));
        picTable2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                picTable2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        picTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                picTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(picTable2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 950, 130));

        btnSave4.setBackground(new java.awt.Color(0, 153, 204));
        btnSave4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave4.setForeground(new java.awt.Color(102, 0, 51));
        btnSave4.setText("SAVE");
        btnSave4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, 100, 40));

        comStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comStatus.setForeground(new java.awt.Color(51, 0, 51));
        comStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Booked", "Pickup", "In Transit", "Out For Delivery", "Delivered" }));
        getContentPane().add(comStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 200, 40));

        btmReset.setBackground(new java.awt.Color(0, 153, 204));
        btmReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btmReset.setForeground(new java.awt.Color(102, 0, 51));
        btmReset.setText("RESET");
        btmReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmResetActionPerformed(evt);
            }
        });
        getContentPane().add(btmReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 100, 40));

        btnUpdate2.setBackground(new java.awt.Color(0, 153, 204));
        btnUpdate2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate2.setForeground(new java.awt.Color(102, 0, 51));
        btnUpdate2.setText("UPDATE");
        btnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 100, 40));

        btnDelete.setBackground(new java.awt.Color(0, 153, 204));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(102, 0, 51));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 100, 40));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Order/body3.jpg"))); // NOI18N
        jLabel37.setText(" ");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 960, 600));

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderTracking/backBtn.png"))); // NOI18N
        btnBack.setText(" ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 50));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Status");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 92, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void picTable2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_picTable2AncestorAdded

    }//GEN-LAST:event_picTable2AncestorAdded

    private void picTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picTable2MouseClicked
        DefaultTableModel model = (DefaultTableModel) picTable2.getModel();
        int row = picTable2.getSelectedRow();
        String id = (String) model.getValueAt(row, 0);
        String tracId = (String) model.getValueAt(row, 1);
        String name = (String) model.getValueAt(row, 2);
        String adress = (String) model.getValueAt(row, 3);
        String phone = (String) model.getValueAt(row, 4);
        String date = (String) model.getValueAt(row, 5);
        String docType = (String) model.getValueAt(row, 6);
        String contant = (String) model.getValueAt(row, 7);
        String waigth = (String) model.getValueAt(row, 8);
        String qty = (String) model.getValueAt(row, 9);
        String amount = (String) model.getValueAt(row, 10);
        String nameS = (String) model.getValueAt(row, 11);
        String adressT = (String) model.getValueAt(row, 12);
        String phoneS = (String) model.getValueAt(row, 13);
        String status = (String) model.getValueAt(row, 14);

        tfDLViD.setText(String.valueOf(id));
        tfTrackId.setText(String.valueOf(tracId));
        tfNameP.setText(name);
        adressP.setText(adress);
        tfphoneP.setText(phone);
        tfDate.setText(date);
        coomDOtypP.setSelectedItem(docType);
        tfContentsP.setText(contant);
        comWgtP.setSelectedItem(waigth);
        tfQuantityP.setText(String.valueOf(qty));
        tfAmountP.setText(String.valueOf(amount));
        tfnameS.setText(nameS);
        adressS.setText(adressT);
        tfPhoneS.setText(phoneS);
        comStatus.setSelectedItem(status);
    }

    private void loadTable() {
        try {
            DefaultTableModel tModel = (DefaultTableModel) picTable2.getModel();
            Connection conn = DatabaceConnector.dataConnect();
            String sql = "SELECT * FROM informetion";
            PreparedStatement pst = conn.prepareStatement(sql);
            int rowCount = picTable2.getRowCount();
            for (int i = 0; i < rowCount; i++) {
                tModel.removeRow(0);
            }
            ResultSet result = pst.executeQuery();

            while (result.next()) {
                String id = result.getString(1);
                String tracId = result.getString(2);
                String name = result.getString(3);
                String adress = result.getString(4);
                String phNo = result.getString(5);
                String date = result.getString(6);
                String docType = result.getString(7);
                String contant = result.getString(8);
                String waight = result.getString(9);
                String qty = result.getString(10);
                String amount = result.getString(11);
                String nameS = result.getString(12);
                String adressT = result.getString(13);
                String phNoS = result.getString(14);
                String status = result.getString(15);
                String[] arr = {id, tracId, name, adress, phNo, date, docType, contant, waight, qty, amount, nameS, adressT, phNoS, status};
                tModel.addRow(arr);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_picTable2MouseClicked

    private void btnSave4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave4ActionPerformed

        String id = tfDLViD.getText();
        String trNo = tfTrackId.getText();
        String name = tfNameP.getText();
        String address = adressP.getText();
        String phone = tfphoneP.getText();
        String date = tfDate.getText();
        String dType = (String) coomDOtypP.getSelectedItem();
        String contanc = tfContentsP.getText();
        String wight = (String) comWgtP.getSelectedItem();
        String qantity = tfQuantityP.getText();
        String amount = tfAmountP.getText();
        String nameS = tfnameS.getText();
        String addressS = adressS.getText();
        String phoneS = tfPhoneS.getText();
        String status = (String) comStatus.getSelectedItem();

        String sql = "INSERT INTO informetion (ID, Traking_id,name,adress,phone,date,docoment_type,"
                + "content,waight,quantity,amount,nameS,adressS,phoneS, status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        Connection conn = DatabaceConnector.dataConnect();

        try {
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, id);
            pst.setString(2, trNo);
            pst.setString(3, name);
            pst.setString(4, address);
            pst.setString(5, phone);
            pst.setString(6, date);
            pst.setString(7, dType);
            pst.setString(8, contanc);
            pst.setString(9, wight);
            pst.setString(10, qantity);
            pst.setString(11, amount);
            pst.setString(12, nameS);
            pst.setString(13, addressS);
            pst.setString(14, phoneS);
            pst.setString(15, status);
            int ext = pst.executeUpdate();
            loadTable();
            if (ext > 0) {
                JOptionPane.showMessageDialog(rootPane, "Save Successed");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Save Failed");
            }

        } catch (SQLException ex) {
            System.out.println(ex.getLocalizedMessage());
        }

    }//GEN-LAST:event_btnSave4ActionPerformed

    private void btnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate2ActionPerformed
        
        DefaultTableModel tModel = (DefaultTableModel) picTable2.getModel();

        String id = tfDLViD.getText();
        String trNo = tfTrackId.getText();
        String name = tfNameP.getText();
        String address = adressP.getText();
        String phone = tfphoneP.getText();
        String date = tfDate.getText();
        String dType = (String) coomDOtypP.getSelectedItem();
        String contanc = tfContentsP.getText();
        String wight = (String) comWgtP.getSelectedItem();
        String qantity = tfQuantityP.getText();
        String amount = tfAmountP.getText();
        String nameS = tfnameS.getText();
        String addressS = adressS.getText();
        String phoneS = tfPhoneS.getText();
        String status = (String) comStatus.getSelectedItem();

        Connection conn = DatabaceConnector.dataConnect();
        String sql = "UPDATE informetion set Traking_id=?, name=?,  adress=?, phone=?, "
                + "date=?, docoment_type=?, Content=?,  waight=?, quantity=?, amount=?, nameS=?, "
                + "adressS=?, phoneS=?,status=? WHERE ID= ?";
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(15, id);
            pst.setString(1, trNo);
            pst.setString(2, name);
            pst.setString(3, address);
            pst.setString(4, phone);
            pst.setString(5, date);
            pst.setString(6, dType);
            pst.setString(7, contanc);
            pst.setString(8, wight);
            pst.setString(9, qantity);
            pst.setString(10, amount);
            pst.setString(11, nameS);
            pst.setString(12, addressS);
            pst.setString(13, phoneS);
            pst.setString(14, status); 
            int rst = pst.executeUpdate(); 
            if (rst > 0) {
                JOptionPane.showMessageDialog(rootPane, "Update finished successfully");
                loadTable();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Update Failed");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnUpdate2ActionPerformed

    private void btmResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmResetActionPerformed
        tfDLViD.setText(null);
        tfTrackId.setText(null);
        tfNameP.setText(null);
        adressP.setText(null);
        tfphoneP.setText(null);
        tfDate.setText(null);
        coomDOtypP.setSelectedItem(null);
        tfContentsP.setText(null);
        comWgtP.setSelectedItem(null);
        tfQuantityP.setText(null);
        tfAmountP.setText(null);
        tfnameS.setText(null);
        adressS.setText(null);
        tfPhoneS.setText(null);
        comStatus.setSelectedItem(null);
        btmReset.setEnabled(false);
    }//GEN-LAST:event_btmResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) picTable2.getModel();
            Connection conn = DatabaceConnector.dataConnect();
            String sql = "DELETE FROM informetion WHERE ID= ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            String id = tfDLViD.getText();
            pst.setInt(1, Integer.parseInt(id));
            int del = pst.executeUpdate();
            if (del > 0) {
                JOptionPane.showMessageDialog(null, "Deleted Successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Deleted Faild");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btmNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmNextActionPerformed
        setVisible(false);
        new castomarCopy().setVisible(true);
    }//GEN-LAST:event_btmNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea adressP;
    private javax.swing.JTextArea adressS;
    private javax.swing.JButton btmNext;
    private javax.swing.JButton btmReset;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnSave4;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnUpdate2;
    private javax.swing.JComboBox<String> comStatus;
    private javax.swing.JComboBox<String> comWgt2;
    private javax.swing.JComboBox<String> comWgtP;
    private javax.swing.JComboBox<String> coomDOtypP;
    private javax.swing.JComboBox<String> coomDOtype2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable picTable2;
    private javax.swing.JTextArea texaria3;
    private javax.swing.JTextField tfAmount2;
    private javax.swing.JTextField tfAmountP;
    private javax.swing.JTextField tfContents2;
    private javax.swing.JTextField tfContentsP;
    private javax.swing.JTextField tfDLViD;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfId2;
    private javax.swing.JTextField tfName3;
    private javax.swing.JTextField tfNameP;
    private javax.swing.JTextField tfPhone3;
    private javax.swing.JTextField tfPhoneS;
    private javax.swing.JTextField tfQuantity2;
    private javax.swing.JTextField tfQuantityP;
    private javax.swing.JTextField tfTrackId;
    private javax.swing.JTextField tfTrakingNo2;
    private javax.swing.JTextField tfnameS;
    private javax.swing.JTextField tfphoneP;
    // End of variables declaration//GEN-END:variables
}
