/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderTracking;

import com.homePage.HomePage;
import com.util.DatabaceConnector;
import java.awt.List;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Khalil
 */
public class PendingOrder extends javax.swing.JFrame {

    /**
     * Creates new form PendingOrder
     */
    public PendingOrder() {
        initComponents();
        setLocationRelativeTo(null);
        //Calendar();
    }

    public void Calendar() {
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        tfDate.setText(+year + "-" + (month + 1) + "-" + day);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public PendingOrder(int id2) {

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfTrackId = new javax.swing.JTextField();
        tfDate = new javax.swing.JTextField();
        tfDelId = new javax.swing.JTextField();
        tfPhone = new javax.swing.JTextField();
        tfContent = new javax.swing.JTextField();
        tfDestination = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSarch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tdSarchId = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        tfstatus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        tfDestination1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ttack Order");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 818, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Delivery ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, 101, 32));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Tracking No.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 177, 115, 32));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Name:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 133, 92, 32));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Destination");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 232, 110, 32));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Phone No.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 227, 92, 32));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Contants");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 283, 92, 32));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Dalivery Date");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 184, 122, 32));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Status");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 283, 92, 32));

        tfName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfName.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 134, 139, 32));

        tfTrackId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfTrackId.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfTrackId, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 184, 139, 32));

        tfDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfDate.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 185, 139, 32));

        tfDelId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfDelId.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfDelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 134, 139, 32));

        tfPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfPhone.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 233, 139, 32));

        tfContent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfContent.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 284, 139, 32));

        tfDestination.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfDestination.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 233, 139, 32));

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/login/backBtn-removebg-preview.png"))); // NOI18N
        btnBack.setText(" ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 80, 50));

        btnSarch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSarch.setText("SARCH");
        btnSarch.setToolTipText("");
        btnSarch.setActionCommand("");
        btnSarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSarchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSarch, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 66, -1, 33));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Delivery ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 66, 82, 32));

        tdSarchId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tdSarchId.setForeground(new java.awt.Color(0, 102, 102));
        tdSarchId.setText(" ");
        getContentPane().add(tdSarchId, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 67, 124, 32));

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 113, 36));

        tfstatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfstatus.setForeground(new java.awt.Color(153, 0, 102));
        getContentPane().add(tfstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 140, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderTracking/pendi2.gif"))); // NOI18N
        jLabel3.setText(" ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 820, 490));

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 140, -1));

        tfDestination1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfDestination1.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfDestination1, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 233, 139, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSarchActionPerformed
        String id = tdSarchId.getText();

        Connection conn = DatabaceConnector.dataConnect();
        String sql = "select * from informetion where ID = '" + id + "'";
        try {
            PreparedStatement pst = conn.prepareStatement(sql);

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                tfDelId.setText(rs.getString(1));
                tfTrackId.setText(rs.getString(2));
                tfName.setText(rs.getString(3));
                tfDate.setText(rs.getString(6));
                tfDestination.setText(rs.getString(13));
                tfPhone.setText(rs.getString(14));
                tfContent.setText(rs.getString(8));
                tfstatus.setText(rs.getString(15));
                //System.out.println(rs.getString(8));

            }
        } catch (SQLException ex) {
            System.out.println(ex.getLocalizedMessage());
        }

    }//GEN-LAST:event_btnSarchActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            tfDelId.print();

        } catch (PrinterException px) {
            System.out.println(px.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendingOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendingOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendingOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendingOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendingOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSarch;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField tdSarchId;
    private javax.swing.JTextField tfContent;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfDelId;
    private javax.swing.JTextField tfDestination;
    private javax.swing.JTextField tfDestination1;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfTrackId;
    private javax.swing.JTextField tfstatus;
    // End of variables declaration//GEN-END:variables
}
