/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderTracking;

import com.homePage.HomePage;

/**
 *
 * @author Khalil
 */
public class TrackOrder extends javax.swing.JFrame {

    /**
     * Creates new form TrackOrder
     */
    public TrackOrder() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfId1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfId2 = new javax.swing.JTextField();
        tfId3 = new javax.swing.JTextField();
        tfId4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfId5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfId6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfId7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        anotherOrder = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ttack Order");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 829, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Dalivery Status ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 338, -1, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Delivery ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 181, 101, 32));

        tfId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfId.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 182, 139, 32));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Tracking No.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 242, 115, 32));

        tfId1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfId1.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 242, 139, 34));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Name:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 181, 92, 32));

        tfId2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfId2.setForeground(new java.awt.Color(0, 153, 51));
        getContentPane().add(tfId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 339, 139, 32));

        tfId3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfId3.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 182, 139, 32));

        tfId4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfId4.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfId4, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 288, 139, 32));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Destination");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 287, 110, 32));

        tfId5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfId5.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfId5, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 353, 139, 32));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Phone No.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 287, 92, 32));

        tfId6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfId6.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfId6, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 243, 139, 32));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Contants");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 352, 92, 32));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Dalivery Date");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 242, 122, 32));

        tfId7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfId7.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(tfId7, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 288, 139, 32));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Delivery ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 62, 82, 32));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 102));
        jTextField1.setText(" ");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 63, 124, 32));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("SARCH");
        jButton1.setToolTipText("");
        jButton1.setActionCommand("");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 62, -1, 33));

        anotherOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        anotherOrder.setText("Another Order");
        anotherOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anotherOrderActionPerformed(evt);
            }
        });
        getContentPane().add(anotherOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 443, 139, 36));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("PRINT");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 450, 113, 36));

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/login/backBtn-removebg-preview.png"))); // NOI18N
        btnBack.setText(" ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 493, 90, 60));

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderTracking/coverPh.png"))); // NOI18N
        jLabel3.setText(" ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 830, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void anotherOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anotherOrderActionPerformed
         setVisible(false);
        new PendingOrder().setVisible(true);
    }//GEN-LAST:event_anotherOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anotherOrder;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfId1;
    private javax.swing.JTextField tfId2;
    private javax.swing.JTextField tfId3;
    private javax.swing.JTextField tfId4;
    private javax.swing.JTextField tfId5;
    private javax.swing.JTextField tfId6;
    private javax.swing.JTextField tfId7;
    // End of variables declaration//GEN-END:variables
}
